name: glamcart-frontend
services:
- name: frontend
  github:
    repo: ayeshasnoorr44/glamcart-frontend
    branch: main
  build_command: npm ci && npm run build
  run_command: npm start
  http_port: 3000
  envs:
  - key: NEXT_PUBLIC_API_URL
    value: http://159.89.170.225:5000
  - key: NODE_ENV
    value: production
