name: glamcart-frontend
services:
- name: frontend
  github:
    repo: ayeshasnoorr44/glamcart-frontend
    branch: main
  build_command: npm ci --legacy-peer-deps && npm run build
  run_command: npm start
  http_port: 3000
  envs:
  - key: NEXT_PUBLIC_API_URL
    value: https://glamcart-backend.ondigitalocean.app
  - key: NODE_ENV
    value: production
