name: glamcart-backend
services:
- name: backend
  github:
    repo: ayeshasnoorr44/glamcart-backend
    branch: main
  build_command: npm ci && npm run build
  run_command: npm start
  http_port: 5000
  envs:
  - key: MONGODB_URI
    value: ${MONGODB_URI}
  - key: NODE_ENV
    value: production
  - key: CORS_ORIGIN
    value: https://glamcart-frontend.ondigitalocean.app
  - key: PORT
    value: 5000
